import Foundation

struct DefaultAffirmations {
    static let focus: [Affirmation] = [
        Affirmation(theme: .focus, text: "I choose purpose over distraction"),
        Affirmation(theme: .focus, text: "My time is valuable and intentional"),
        Affirmation(theme: .focus, text: "I am fully present in this moment"),
        Affirmation(theme: .focus, text: "I focus on what truly matters"),
        Affirmation(theme: .focus, text: "I act with discipline and grace"),
        Affirmation(theme: .focus, text: "I complete tasks one at a time"),
        Affirmation(theme: .focus, text: "I am focused and free from distractions"),
        Affirmation(theme: .focus, text: "Every action I take moves me forward"),
        Affirmation(theme: .focus, text: "I take control of my time"),
        Affirmation(theme: .focus, text: "My mind is clear and sharp"),
        Affirmation(theme: .focus, text: "I bring energy to my work"),
        Affirmation(theme: .focus, text: "I prioritize progress over perfection"),
        Affirmation(theme: .focus, text: "I protect my attention fiercely"),
        Affirmation(theme: .focus, text: "My focus creates my future"),
        Affirmation(theme: .focus, text: "I stay grounded in my goals"),
        Affirmation(theme: .focus, text: "I am free from the pull of distraction"),
        Affirmation(theme: .focus, text: "My time online serves my growth"),
        Affirmation(theme: .focus, text: "I act with intention today"),
        Affirmation(theme: .focus, text: "I choose action over avoidance"),
        Affirmation(theme: .focus, text: "I show up for myself fully")
    ]
    static let confidence: [Affirmation] = [
        Affirmation(theme: .confidence, text: "I am enough as I am"),
        Affirmation(theme: .confidence, text: "I honor my uniqueness"),
        Affirmation(theme: .confidence, text: "My self-worth is not defined by others"),
        Affirmation(theme: .confidence, text: "I value myself deeply"),
        Affirmation(theme: .confidence, text: "I trust my voice"),
        Affirmation(theme: .confidence, text: "I embrace my true self"),
        Affirmation(theme: .confidence, text: "I am proud of who I am"),
        Affirmation(theme: .confidence, text: "I walk confidently in the world"),
        Affirmation(theme: .confidence, text: "I radiate self-respect"),
        Affirmation(theme: .confidence, text: "I am whole and worthy"),
        Affirmation(theme: .confidence, text: "I celebrate my journey"),
        Affirmation(theme: .confidence, text: "My presence matters"),
        Affirmation(theme: .confidence, text: "I own my story"),
        Affirmation(theme: .confidence, text: "I stand tall in my truth"),
        Affirmation(theme: .confidence, text: "I trust my choices"),
        Affirmation(theme: .confidence, text: "I love myself unconditionally"),
        Affirmation(theme: .confidence, text: "My worth is infinite"),
        Affirmation(theme: .confidence, text: "I am my own greatest ally"),
        Affirmation(theme: .confidence, text: "I honor my needs"),
        Affirmation(theme: .confidence, text: "I deserve peace and happiness")
    ]
    static let gratitude: [Affirmation] = [
        Affirmation(theme: .gratitude, text: "I am grateful for today"),
        Affirmation(theme: .gratitude, text: "I appreciate this moment"),
        Affirmation(theme: .gratitude, text: "I give thanks for all I have"),
        Affirmation(theme: .gratitude, text: "Gratitude fills my heart"),
        Affirmation(theme: .gratitude, text: "I find joy in small things"),
        Affirmation(theme: .gratitude, text: "I welcome blessings with gratitude"),
        Affirmation(theme: .gratitude, text: "I honor life’s simple gifts"),
        Affirmation(theme: .gratitude, text: "I cherish the present"),
        Affirmation(theme: .gratitude, text: "I appreciate those who love me"),
        Affirmation(theme: .gratitude, text: "I express gratitude openly"),
        Affirmation(theme: .gratitude, text: "My heart is full of gratitude"),
        Affirmation(theme: .gratitude, text: "I give thanks for my breath"),
        Affirmation(theme: .gratitude, text: "I see beauty everywhere"),
        Affirmation(theme: .gratitude, text: "I am thankful for my journey"),
        Affirmation(theme: .gratitude, text: "I appreciate my growth"),
        Affirmation(theme: .gratitude, text: "I hold gratitude for my body"),
        Affirmation(theme: .gratitude, text: "I acknowledge life’s abundance"),
        Affirmation(theme: .gratitude, text: "I am thankful for today’s opportunities"),
        Affirmation(theme: .gratitude, text: "I embrace today with gratitude"),
        Affirmation(theme: .gratitude, text: "I honor this life")
    ]
    static let peace: [Affirmation] = [
        Affirmation(theme: .peace, text: "I breathe deeply and calmly"),
        Affirmation(theme: .peace, text: "Peace begins within me"),
        Affirmation(theme: .peace, text: "I am centered and present"),
        Affirmation(theme: .peace, text: "I surrender to the moment"),
        Affirmation(theme: .peace, text: "My mind is calm and clear"),
        Affirmation(theme: .peace, text: "I release what I cannot control"),
        Affirmation(theme: .peace, text: "I cultivate inner stillness"),
        Affirmation(theme: .peace, text: "I find peace in silence"),
        Affirmation(theme: .peace, text: "I trust the universe’s flow"),
        Affirmation(theme: .peace, text: "I honor my inner voice"),
        Affirmation(theme: .peace, text: "I carry peace within"),
        Affirmation(theme: .peace, text: "I return to my breath"),
        Affirmation(theme: .peace, text: "I embrace calm in all I do"),
        Affirmation(theme: .peace, text: "I invite peace into this moment"),
        Affirmation(theme: .peace, text: "My spirit is grounded"),
        Affirmation(theme: .peace, text: "I walk in harmony"),
        Affirmation(theme: .peace, text: "I trust life’s unfolding"),
        Affirmation(theme: .peace, text: "I am guided by peace"),
        Affirmation(theme: .peace, text: "I release tension from my body"),
        Affirmation(theme: .peace, text: "I embrace simplicity and peace")
    ]
    static let relationships: [Affirmation] = [
        Affirmation(theme: .relationships, text: "I nurture healthy connections"),
        Affirmation(theme: .relationships, text: "I bring love and kindness to others"),
        Affirmation(theme: .relationships, text: "I communicate with honesty and care"),
        Affirmation(theme: .relationships, text: "I honor my boundaries"),
        Affirmation(theme: .relationships, text: "I am present with those I love"),
        Affirmation(theme: .relationships, text: "My relationships are built on respect"),
        Affirmation(theme: .relationships, text: "I listen deeply to others"),
        Affirmation(theme: .relationships, text: "I show compassion freely"),
        Affirmation(theme: .relationships, text: "I attract supportive relationships"),
        Affirmation(theme: .relationships, text: "I value meaningful connections"),
        Affirmation(theme: .relationships, text: "I respect others’ journeys"),
        Affirmation(theme: .relationships, text: "I give love without conditions"),
        Affirmation(theme: .relationships, text: "I create space for honesty"),
        Affirmation(theme: .relationships, text: "I surround myself with kindness"),
        Affirmation(theme: .relationships, text: "I honor the people in my life"),
        Affirmation(theme: .relationships, text: "I show up with empathy"),
        Affirmation(theme: .relationships, text: "I forgive with grace"),
        Affirmation(theme: .relationships, text: "I speak with love"),
        Affirmation(theme: .relationships, text: "I foster understanding"),
        Affirmation(theme: .relationships, text: "I cherish my relationships")
    ]
    static let trustingGod: [Affirmation] = [
        Affirmation(theme: .trustingGod, text: "I trust God’s plan for my life."),
        Affirmation(theme: .trustingGod, text: "The Lord is my shepherd; I lack nothing. — Psalm 23:1"),
        Affirmation(theme: .trustingGod, text: "God strengthens me every day."),
        Affirmation(theme: .trustingGod, text: "I walk by faith, not by sight. — 2 Corinthians 5:7"),
        Affirmation(theme: .trustingGod, text: "God’s love casts out all fear."),
        Affirmation(theme: .trustingGod, text: "Be still and know that I am God. — Psalm 46:10"),
        Affirmation(theme: .trustingGod, text: "My hope is in the Lord."),
        Affirmation(theme: .trustingGod, text: "The Lord will fight for me; I need only to be still. — Exodus 14:14"),
        Affirmation(theme: .trustingGod, text: "God’s grace is sufficient for me."),
        Affirmation(theme: .trustingGod, text: "I place my trust fully in God."),
        Affirmation(theme: .trustingGod, text: "For I know the plans I have for you, declares the Lord. — Jeremiah 29:11"),
        Affirmation(theme: .trustingGod, text: "I am safe in God’s hands."),
        Affirmation(theme: .trustingGod, text: "I surrender my worries to God."),
        Affirmation(theme: .trustingGod, text: "I have peace because I trust in Him."),
        Affirmation(theme: .trustingGod, text: "The Lord is my refuge and my fortress. — Psalm 91:2"),
        Affirmation(theme: .trustingGod, text: "God’s timing is perfect."),
        Affirmation(theme: .trustingGod, text: "The Lord upholds all who fall. — Psalm 145:14"),
        Affirmation(theme: .trustingGod, text: "I am guided by divine wisdom."),
        Affirmation(theme: .trustingGod, text: "The Lord is near to all who call on Him. — Psalm 145:18"),
        Affirmation(theme: .trustingGod, text: "God is working everything for my good. — Romans 8:28"),
        Affirmation(theme: .trustingGod, text: "I cast all my anxiety on Him because He cares for me. — 1 Peter 5:7"),
        Affirmation(theme: .trustingGod, text: "The joy of the Lord is my strength. — Nehemiah 8:10"),
        Affirmation(theme: .trustingGod, text: "The Lord renews my strength."),
        Affirmation(theme: .trustingGod, text: "God is my light and my salvation. — Psalm 27:1"),
        Affirmation(theme: .trustingGod, text: "I trust in the Lord with all my heart. — Proverbs 3:5"),
        Affirmation(theme: .trustingGod, text: "Faith over fear."),
        Affirmation(theme: .trustingGod, text: "God’s peace guards my heart and mind. — Philippians 4:7"),
        Affirmation(theme: .trustingGod, text: "His mercies are new every morning. — Lamentations 3:23"),
        Affirmation(theme: .trustingGod, text: "The Lord sustains me."),
        Affirmation(theme: .trustingGod, text: "I rest in God's promises."),
        Affirmation(theme: .trustingGod, text: "The Lord is faithful to all His promises. — Psalm 145:13"),
        Affirmation(theme: .trustingGod, text: "My future is in God’s hands."),
        Affirmation(theme: .trustingGod, text: "I have unshakeable faith."),
        Affirmation(theme: .trustingGod, text: "God provides for all my needs."),
        Affirmation(theme: .trustingGod, text: "The Lord will guide me always. — Isaiah 58:11"),
        Affirmation(theme: .trustingGod, text: "The Lord surrounds me with favor as with a shield. — Psalm 5:12"),
        Affirmation(theme: .trustingGod, text: "I trust God’s timing and plans."),
        Affirmation(theme: .trustingGod, text: "I fear no evil, for You are with me. — Psalm 23:4"),
        Affirmation(theme: .trustingGod, text: "I stand firm in faith."),
        Affirmation(theme: .trustingGod, text: "The Lord will strengthen and help me. — Isaiah 41:10"),
        Affirmation(theme: .trustingGod, text: "God's love never fails."),
        Affirmation(theme: .trustingGod, text: "I am never alone; God is always near."),
        Affirmation(theme: .trustingGod, text: "The Lord blesses me and keeps me. — Numbers 6:24"),
        Affirmation(theme: .trustingGod, text: "I let go and let God."),
        Affirmation(theme: .trustingGod, text: "My faith makes me whole. — Matthew 9:22"),
        Affirmation(theme: .trustingGod, text: "God is for me, not against me. — Romans 8:31"),
        Affirmation(theme: .trustingGod, text: "I have peace that surpasses all understanding. — Philippians 4:7"),
        Affirmation(theme: .trustingGod, text: "The Lord hears my prayers."),
        Affirmation(theme: .trustingGod, text: "I rejoice in hope."),
        Affirmation(theme: .trustingGod, text: "Nothing is impossible with God. — Luke 1:37")
    ]
    static let all: [Affirmation] = focus + confidence + gratitude + peace + relationships + trustingGod
} 